# Generated by Django 5.1.6 on 2025-02-06 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                ("address", models.TextField(verbose_name="Direccion")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad en Stock"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de compra"
                    ),
                ),
                (
                    "price_sale",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de venta"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="inventory.store",
                        verbose_name="Almacen",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="inventory.unit",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["id"], name="inventory_p_id_418c5b_idx"),
                    models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
                    models.Index(
                        fields=["-created"], name="inventory_p_created_e283f3_idx"
                    ),
                ],
            },
        ),
    ]
