# Generated by Django 5.1.6 on 2025-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que se creó el objeto",
                verbose_name="Creado",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha en la que se modificó el objeto",
                verbose_name="Modificado",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que se creó el objeto",
                verbose_name="Creado",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha en la que se modificó el objeto",
                verbose_name="Modificado",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que se creó el objeto",
                verbose_name="Creado",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha en la que se modificó el objeto",
                verbose_name="Modificado",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que se creó el objeto",
                verbose_name="Creado",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha en la que se modificó el objeto",
                verbose_name="Modificado",
            ),
        ),
    ]
