# Generated by Django 5.1.6 on 2025-02-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"verbose_name": "Almacen", "verbose_name_plural": "Almacenes"},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"verbose_name": "Unidad", "verbose_name_plural": "Unidades"},
        ),
    ]
