# Generated by Django 5.1.6 on 2025-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_category_created_alter_category_modified_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["active"], name="inventory_u_active_3e387d_idx"),
        ),
    ]
