# Generated by Django 5.1.6 on 2025-02-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_unit_inventory_u_active_3e387d_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descripcion"),
        ),
    ]
