# Generated by Django 5.1.6 on 2025-02-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='store',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted'),
        ),
    ]
