# Generated by Django 5.1.6 on 2025-02-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_unit_quantity_alter_store_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nombre"),
        ),
    ]
